// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// UCompC
SEXP UCompC(SEXP commands, SEXP ys, SEXP us, SEXP models, SEXP hs, SEXP lambdas, SEXP outliers, SEXP tTests, SEXP criterions, SEXP periodss, SEXP rhoss, SEXP verboses, SEXP stepwises, SEXP p0s, SEXP armas, SEXP TVPs, SEXP seass, SEXP trendOptionss, SEXP seasonalOptionss, SEXP irregularOptionss, SEXP nsims, SEXP seeds, SEXP lambdaLowers, SEXP aEndIns, SEXP PEndIns, SEXP innVarIns, SEXP betaAugIns);
RcppExport SEXP _muse_UCompC(SEXP commandsSEXP, SEXP ysSEXP, SEXP usSEXP, SEXP modelsSEXP, SEXP hsSEXP, SEXP lambdasSEXP, SEXP outliersSEXP, SEXP tTestsSEXP, SEXP criterionsSEXP, SEXP periodssSEXP, SEXP rhossSEXP, SEXP verbosesSEXP, SEXP stepwisesSEXP, SEXP p0sSEXP, SEXP armasSEXP, SEXP TVPsSEXP, SEXP seassSEXP, SEXP trendOptionssSEXP, SEXP seasonalOptionssSEXP, SEXP irregularOptionssSEXP, SEXP nsimsSEXP, SEXP seedsSEXP, SEXP lambdaLowersSEXP, SEXP aEndInsSEXP, SEXP PEndInsSEXP, SEXP innVarInsSEXP, SEXP betaAugInsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type commands(commandsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< SEXP >::type us(usSEXP);
    Rcpp::traits::input_parameter< SEXP >::type models(modelsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type hs(hsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< SEXP >::type outliers(outliersSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tTests(tTestsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type criterions(criterionsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type periodss(periodssSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhoss(rhossSEXP);
    Rcpp::traits::input_parameter< SEXP >::type verboses(verbosesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type stepwises(stepwisesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type p0s(p0sSEXP);
    Rcpp::traits::input_parameter< SEXP >::type armas(armasSEXP);
    Rcpp::traits::input_parameter< SEXP >::type TVPs(TVPsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type seass(seassSEXP);
    Rcpp::traits::input_parameter< SEXP >::type trendOptionss(trendOptionssSEXP);
    Rcpp::traits::input_parameter< SEXP >::type seasonalOptionss(seasonalOptionssSEXP);
    Rcpp::traits::input_parameter< SEXP >::type irregularOptionss(irregularOptionssSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nsims(nsimsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type seeds(seedsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambdaLowers(lambdaLowersSEXP);
    Rcpp::traits::input_parameter< SEXP >::type aEndIns(aEndInsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type PEndIns(PEndInsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type innVarIns(innVarInsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type betaAugIns(betaAugInsSEXP);
    rcpp_result_gen = Rcpp::wrap(UCompC(commands, ys, us, models, hs, lambdas, outliers, tTests, criterions, periodss, rhoss, verboses, stepwises, p0s, armas, TVPs, seass, trendOptionss, seasonalOptionss, irregularOptionss, nsims, seeds, lambdaLowers, aEndIns, PEndIns, innVarIns, betaAugIns));
    return rcpp_result_gen;
END_RCPP
}
// UCompARMAC
SEXP UCompARMAC(SEXP ys, SEXP arOrders_, SEXP maOrders_, SEXP armaLags_, SEXP criterion_);
RcppExport SEXP _muse_UCompARMAC(SEXP ysSEXP, SEXP arOrders_SEXP, SEXP maOrders_SEXP, SEXP armaLags_SEXP, SEXP criterion_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< SEXP >::type arOrders_(arOrders_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type maOrders_(maOrders_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type armaLags_(armaLags_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type criterion_(criterion_SEXP);
    rcpp_result_gen = Rcpp::wrap(UCompARMAC(ys, arOrders_, maOrders_, armaLags_, criterion_));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_muse_UCompC", (DL_FUNC) &_muse_UCompC, 27},
    {"_muse_UCompARMAC", (DL_FUNC) &_muse_UCompARMAC, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_muse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
