# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ctllSim <- function(states, noiseEta, noiseEpsilon, logValue) {
    .Call('_muse_ctllSim', PACKAGE = 'muse', states, noiseEta, noiseEpsilon, logValue)
}

UCompC <- function(commands, ys, us, models, hs, lambdas, outliers, tTests, criterions, periodss, rhoss, verboses, stepwises, p0s, armas, TVPs, seass, trendOptionss, seasonalOptionss, irregularOptionss) {
    .Call('_muse_UCompC', PACKAGE = 'muse', commands, ys, us, models, hs, lambdas, outliers, tTests, criterions, periodss, rhoss, verboses, stepwises, p0s, armas, TVPs, seass, trendOptionss, seasonalOptionss, irregularOptionss)
}

