# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ctllSim <- function(states, noiseEta, noiseEpsilon, logValue) {
    .Call('_muse_ctllSim', PACKAGE = 'muse', states, noiseEta, noiseEpsilon, logValue)
}

MSOEc <- function(commands, ys, us, models, periodss, rhoss, hs, tTests, criterions, ps, rubbish2s, rubbishs, verboses, stepwises, estimOks, p0s, vs, yFitVs, nonStationaryTermss, rubbish3s, harmonicss, criterias, cycleLimitss, betass, typeOutlierss, TVPs, trendOptionss, seasonalOptionss, irregularOptionss) {
    .Call('_muse_MSOEc', PACKAGE = 'muse', commands, ys, us, models, periodss, rhoss, hs, tTests, criterions, ps, rubbish2s, rubbishs, verboses, stepwises, estimOks, p0s, vs, yFitVs, nonStationaryTermss, rubbish3s, harmonicss, criterias, cycleLimitss, betass, typeOutlierss, TVPs, trendOptionss, seasonalOptionss, irregularOptionss)
}

INTLEVELc <- function(command, y, us, h, obsEq, verbose, p0s, logTransform) {
    .Call('_muse_INTLEVELc', PACKAGE = 'muse', command, y, us, h, obsEq, verbose, p0s, logTransform)
}

